# https://aws.amazon.com/blogs/opensource/getting-started-with-spring-boot-on-aws-part-1/
cloud:
  aws:
    assumeRoleARN: arn:aws:iam::039316342888:role/AllowMyAwesomeWebAppToTalkToAWSServicesRole
    roleSessionName: my-awesome-aws-app-session
    region:
      static: us-east-1

application:
  bucket:
    name: my-aws-demo-app-images-bucket